### ISSUE TITLE
PROPOSAL: Allow users to write light scripts

### ISSUE THREAD

**Issue by csakai** [schlueter/hueview#6]
It would be cool if we implement some simple store where users can save simple macros for lights.  

Some simple examples:
- Color swatches
- Mood-lighting
- Adjust multiple lights with one command  

Some more complicated examples:
- Flash a certain color from one command
- Set an interval to randomize (potentially a user-selected range of) colors (cool trick for parties, similar to the shell script you wrote that one time)

**Comment by schlueter** [comment]
Much of that already exists in the hub's api: [scenes](http://www.developers.meethue.com/documentation/scenes-api) for color swatches and mood-lighting, [groups](http://www.developers.meethue.com/documentation/groups-api), [flash and interval (not user selected)](http://www.developers.meethue.com/documentation/lights-api) can be affected with currently unimplemented attributes of the lights api. Feel free to submit PRs implementing any of these.
